#!/bin/sh -eu

################################################################################
# The directory holding your source code and stack.yaml file:
SRC_DIR=~/.xmonad

################################################################################
# The name of the executable produced by stack.  This comes from the
# executable section of your Cabal file.
EXE_NAME=xmonad-wamaral

################################################################################
# This script will be given a single argument, the path to the
# executable it should produce.
output_file=$1; shift

################################################################################
cd $SRC_DIR
stack install
mv $output_file /tmp/${EXE_NAME}-old
rm /tmp/${EXE_NAME}-old
cp -u "$(stack path --local-install-root)/bin/${EXE_NAME}" $output_file
