flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- gtk-traymanager-0.1.6
- taffybar-0.4.6
- X11-xft-0.3.1
- xmonad-contrib-0.13
- dbus-0.10.12
- libxml-sax-0.7.5
- fuzzy-0.1.0.0
resolver: lts-8.6
